import fs from 'fs'
import path from 'path'

const readRootFile = (name: string) =>
  fs.readFileSync(path.join(__dirname, '..', name), 'utf8')

describe('project setup', () => {
  // src/index.css is generated by postcss and is git-ignored, so every script
  // that compiles the app needs a pre step building it first. Otherwise the
  // import in src/index.tsx fails with "Module not found" on a fresh clone.
  it('builds src/index.css before starting and before building', () => {
    const { scripts } = JSON.parse(readRootFile('package.json'))

    expect(scripts.prestart).toContain('-o src/index.css')
    expect(scripts.prebuild).toContain('-o src/index.css')
  })

  // Without this a Windows clone gets CRLF files, and every one of them then
  // fails the prettier/prettier rule that eslint runs during start and build.
  it('checks text files out with LF line endings', () => {
    const rules = readRootFile('.gitattributes')
      .split('\n')
      .map((line) => line.trim())

    expect(rules).toContain('* text=auto eol=lf')
    expect(rules).toContain('*.sh text eol=lf')
  })
})
